//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDroidApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoanDroidApp.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT.
        /// </summary>
        public static string ACCOUNT_ {
            get {
                return ResourceManager.GetString("ACCOUNT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account holder.
        /// </summary>
        public static string accountholder {
            get {
                return ResourceManager.GetString("accountholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new client.
        /// </summary>
        public static string Addnewclient {
            get {
                return ResourceManager.GetString("Addnewclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new investor.
        /// </summary>
        public static string Addnewinvestor {
            get {
                return ResourceManager.GetString("Addnewinvestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string ADDRESS_ {
            get {
                return ResourceManager.GetString("ADDRESS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Reserved.
        /// </summary>
        public static string AllReserved {
            get {
                return ResourceManager.GetString("AllReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMOUNT.
        /// </summary>
        public static string AMOUNT_ {
            get {
                return ResourceManager.GetString("AMOUNT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVATAR.
        /// </summary>
        public static string AVATAR_ {
            get {
                return ResourceManager.GetString("AVATAR_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank city.
        /// </summary>
        public static string bankcity {
            get {
                return ResourceManager.GetString("bankcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank country.
        /// </summary>
        public static string bankcountry {
            get {
                return ResourceManager.GetString("bankcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank name.
        /// </summary>
        public static string bankname {
            get {
                return ResourceManager.GetString("bankname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank region.
        /// </summary>
        public static string bankregion {
            get {
                return ResourceManager.GetString("bankregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank street.
        /// </summary>
        public static string bankstreet {
            get {
                return ResourceManager.GetString("bankstreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swift Bic number.
        /// </summary>
        public static string bicnumber {
            get {
                return ResourceManager.GetString("bicnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC NUMBER.
        /// </summary>
        public static string BICNUMBER_ {
            get {
                return ResourceManager.GetString("BICNUMBER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string cardnumber {
            get {
                return ResourceManager.GetString("cardnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITY.
        /// </summary>
        public static string CITY_ {
            get {
                return ResourceManager.GetString("CITY_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIENT.
        /// </summary>
        public static string CLIENT_ {
            get {
                return ResourceManager.GetString("CLIENT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Dialog.
        /// </summary>
        public static string ClientDialog {
            get {
                return ResourceManager.GetString("ClientDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinet Payment Option.
        /// </summary>
        public static string ClientPaymentDialog {
            get {
                return ResourceManager.GetString("ClientPaymentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients Management.
        /// </summary>
        public static string ClientsManagement {
            get {
                return ResourceManager.GetString("ClientsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Projects.
        /// </summary>
        public static string CompletedProjects {
            get {
                return ResourceManager.GetString("CompletedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contactus {
            get {
                return ResourceManager.GetString("Contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of clients.
        /// </summary>
        public static string Countofclient {
            get {
                return ResourceManager.GetString("Countofclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of investors.
        /// </summary>
        public static string Countofinvestor {
            get {
                return ResourceManager.GetString("Countofinvestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTRY.
        /// </summary>
        public static string COUNTRY_ {
            get {
                return ResourceManager.GetString("COUNTRY_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a role.
        /// </summary>
        public static string Createarole {
            get {
                return ResourceManager.GetString("Createarole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a user.
        /// </summary>
        public static string Createauser {
            get {
                return ResourceManager.GetString("Createauser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an investment.
        /// </summary>
        public static string CreateInvestment {
            get {
                return ResourceManager.GetString("CreateInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a request.
        /// </summary>
        public static string CreateRequest {
            get {
                return ResourceManager.GetString("CreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCY.
        /// </summary>
        public static string CURRENCY_ {
            get {
                return ResourceManager.GetString("CURRENCY_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to department.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPARTMENT.
        /// </summary>
        public static string DEPARTMENT_ {
            get {
                return ResourceManager.GetString("DEPARTMENT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        public static string DESCRIPTION_ {
            get {
                return ResourceManager.GetString("DESCRIPTION_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EMAIL_ {
            get {
                return ResourceManager.GetString("EMAIL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPIRATION.
        /// </summary>
        public static string EXPIRATION_ {
            get {
                return ResourceManager.GetString("EXPIRATION_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string expirationdate {
            get {
                return ResourceManager.GetString("expirationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast &amp; Easy Application Process.
        /// </summary>
        public static string FastEasyApplicationProcess {
            get {
                return ResourceManager.GetString("FastEasyApplicationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Loan Amount.
        /// </summary>
        public static string FastEasyApplicationProcess1 {
            get {
                return ResourceManager.GetString("FastEasyApplicationProcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit the loan amount by fill out our loan request form. If you have no account in our system, you need to register yourself first..
        /// </summary>
        public static string FastEasyApplicationProcess1Text {
            get {
                return ResourceManager.GetString("FastEasyApplicationProcess1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Your Loan.
        /// </summary>
        public static string FastEasyApplicationProcess2 {
            get {
                return ResourceManager.GetString("FastEasyApplicationProcess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will check your request with your payment information. And then if your information is valid, we will inform approved decision you..
        /// </summary>
        public static string FastEasyApplicationProcess2Text {
            get {
                return ResourceManager.GetString("FastEasyApplicationProcess2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Your Cash.
        /// </summary>
        public static string FastEasyApplicationProcess3 {
            get {
                return ResourceManager.GetString("FastEasyApplicationProcess3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw loan cash in your account to your payment option..
        /// </summary>
        public static string FastEasyApplicationProcess3Text {
            get {
                return ResourceManager.GetString("FastEasyApplicationProcess3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We directly connect people who need a loan with people who want to invest their money. In this way we achieve that the borrower pays less interest and that the one who invests their money earns good returns..
        /// </summary>
        public static string FastEasyApplicationProcessText {
            get {
                return ResourceManager.GetString("FastEasyApplicationProcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial chart.
        /// </summary>
        public static string Financialchart {
            get {
                return ResourceManager.GetString("Financialchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Loan Services We Offers.
        /// </summary>
        public static string FindLoanServicesWeOffers {
            get {
                return ResourceManager.GetString("FindLoanServicesWeOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will match you with a loan program that meet your financial need. In short term liquidity, by striving to make funds available to them &lt;strong&gt;within 24 hours of application.&lt;/strong&gt;.
        /// </summary>
        public static string FindLoanServicesWeOffersText {
            get {
                return ResourceManager.GetString("FindLoanServicesWeOffersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRSTNAME.
        /// </summary>
        public static string FIRSTNAME_ {
            get {
                return ResourceManager.GetString("FIRSTNAME_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our goal is to provide access to personal loans and education loan, car loan, home loan at insight competitive interest rates lorem ipsums. We are the loan provider, you can use our loan product..
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string forgotpassword {
            get {
                return ResourceManager.GetString("forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently.
        /// </summary>
        public static string frequently {
            get {
                return ResourceManager.GetString("frequently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREQUENTLY.
        /// </summary>
        public static string FREQUENTLY_ {
            get {
                return ResourceManager.GetString("FREQUENTLY_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work?.
        /// </summary>
        public static string howitworks {
            get {
                return ResourceManager.GetString("howitworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree .
        /// </summary>
        public static string iagree {
            get {
                return ResourceManager.GetString("iagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN number.
        /// </summary>
        public static string ibannumber {
            get {
                return ResourceManager.GetString("ibannumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN NUMBER.
        /// </summary>
        public static string IBANNUMBER_ {
            get {
                return ResourceManager.GetString("IBANNUMBER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTEREST.
        /// </summary>
        public static string INTEREST_ {
            get {
                return ResourceManager.GetString("INTEREST_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest of loan.
        /// </summary>
        public static string Interestofloan {
            get {
                return ResourceManager.GetString("Interestofloan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest rate.
        /// </summary>
        public static string interestrate {
            get {
                return ResourceManager.GetString("interestrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal users.
        /// </summary>
        public static string InternalUsers {
            get {
                return ResourceManager.GetString("InternalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        public static string Investment {
            get {
                return ResourceManager.GetString("Investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investments.
        /// </summary>
        public static string Investments {
            get {
                return ResourceManager.GetString("Investments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVESTOR.
        /// </summary>
        public static string INVESTOR_ {
            get {
                return ResourceManager.GetString("INVESTOR_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor Dialog.
        /// </summary>
        public static string InvestorDialog {
            get {
                return ResourceManager.GetString("InvestorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investors Management.
        /// </summary>
        public static string InvestorsManagement {
            get {
                return ResourceManager.GetString("InvestorsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want a loan.
        /// </summary>
        public static string Iwantloan {
            get {
                return ResourceManager.GetString("Iwantloan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to lend.
        /// </summary>
        public static string Iwanttolend {
            get {
                return ResourceManager.GetString("Iwanttolend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to surname.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURNAME.
        /// </summary>
        public static string LASTNAME_ {
            get {
                return ResourceManager.GetString("LASTNAME_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News from Loan Company.
        /// </summary>
        public static string LatestNewsfromLoanCompany {
            get {
                return ResourceManager.GetString("LatestNewsfromLoanCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Calculator.
        /// </summary>
        public static string LoanCalculator {
            get {
                return ResourceManager.GetString("LoanCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Rates.
        /// </summary>
        public static string LoanRates {
            get {
                return ResourceManager.GetString("LoanRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We directly connect people who need a loan with people who want to invest their money..
        /// </summary>
        public static string LoanRatesText {
            get {
                return ResourceManager.GetString("LoanRatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Request.
        /// </summary>
        public static string LoanRequest {
            get {
                return ResourceManager.GetString("LoanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans and investments between people at fair rates.
        /// </summary>
        public static string LoginCaption {
            get {
                return ResourceManager.GetString("LoginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox.
        /// </summary>
        public static string Mailbox {
            get {
                return ResourceManager.GetString("Mailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Request.
        /// </summary>
        public static string MyRequest {
            get {
                return ResourceManager.GetString("MyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string NAME_ {
            get {
                return ResourceManager.GetString("NAME_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER.
        /// </summary>
        public static string NUMBER_ {
            get {
                return ResourceManager.GetString("NUMBER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to office number.
        /// </summary>
        public static string officenumber {
            get {
                return ResourceManager.GetString("officenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFICE NUMBER.
        /// </summary>
        public static string OFFICENUMBER_ {
            get {
                return ResourceManager.GetString("OFFICENUMBER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other phone number.
        /// </summary>
        public static string otherphone {
            get {
                return ResourceManager.GetString("otherphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER NUMBER.
        /// </summary>
        public static string OTHERPTHONE_ {
            get {
                return ResourceManager.GetString("OTHERPTHONE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string PASSWORD_ {
            get {
                return ResourceManager.GetString("PASSWORD_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Loans.
        /// </summary>
        public static string PersonalLoans {
            get {
                return ResourceManager.GetString("PersonalLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number.
        /// </summary>
        public static string phonenumber {
            get {
                return ResourceManager.GetString("phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE NUMBER.
        /// </summary>
        public static string PHONENUMBER_ {
            get {
                return ResourceManager.GetString("PHONENUMBER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we achieve that the borrower pays less interest and that the one who invests their money earns good returns..
        /// </summary>
        public static string ProjectsText {
            get {
                return ResourceManager.GetString("ProjectsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGION.
        /// </summary>
        public static string REGION_ {
            get {
                return ResourceManager.GetString("REGION_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested date.
        /// </summary>
        public static string requesteddate {
            get {
                return ResourceManager.GetString("requesteddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUESTED DATE.
        /// </summary>
        public static string REQUESTEDDATE_ {
            get {
                return ResourceManager.GetString("REQUESTEDDATE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Dialog.
        /// </summary>
        public static string RoleDialog {
            get {
                return ResourceManager.GetString("RoleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role name.
        /// </summary>
        public static string rolename {
            get {
                return ResourceManager.GetString("rolename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Management.
        /// </summary>
        public static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROUTING.
        /// </summary>
        public static string ROUTING_ {
            get {
                return ResourceManager.GetString("ROUTING_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing number.
        /// </summary>
        public static string routingnumber {
            get {
                return ResourceManager.GetString("routingnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes.
        /// </summary>
        public static string Savingchanges {
            get {
                return ResourceManager.GetString("Savingchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving of invest.
        /// </summary>
        public static string Savingofinvest {
            get {
                return ResourceManager.GetString("Savingofinvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving rate.
        /// </summary>
        public static string savingrate {
            get {
                return ResourceManager.GetString("savingrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVING RATE.
        /// </summary>
        public static string SAVINGRATE_ {
            get {
                return ResourceManager.GetString("SAVINGRATE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Rates.
        /// </summary>
        public static string SavingRates {
            get {
                return ResourceManager.GetString("SavingRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the best way to invest, you earn good returns and every month you receive your payments.
        /// </summary>
        public static string SavingRatesText {
            get {
                return ResourceManager.GetString("SavingRatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Url.
        /// </summary>
        public static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans and &lt;strong class=&quot;text-highlight&quot;&gt;investments&lt;/strong&gt;.
        /// </summary>
        public static string slider01_title {
            get {
                return ResourceManager.GetString("slider01_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of our Awesome Testimonials.
        /// </summary>
        public static string SomeofourAwesomeTestimonials {
            get {
                return ResourceManager.GetString("SomeofourAwesomeTestimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string STATUS_ {
            get {
                return ResourceManager.GetString("STATUS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STREET.
        /// </summary>
        public static string STREET_ {
            get {
                return ResourceManager.GetString("STREET_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful loans.
        /// </summary>
        public static string Successfulloans {
            get {
                return ResourceManager.GetString("Successfulloans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURNAME.
        /// </summary>
        public static string SURNAME_ {
            get {
                return ResourceManager.GetString("SURNAME_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms and conditions.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string times {
            get {
                return ResourceManager.GetString("times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMES.
        /// </summary>
        public static string TIMES_ {
            get {
                return ResourceManager.GetString("TIMES_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Histories.
        /// </summary>
        public static string TransactionHistories {
            get {
                return ResourceManager.GetString("TransactionHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted Clients.
        /// </summary>
        public static string TrustedClients {
            get {
                return ResourceManager.GetString("TrustedClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted Investors.
        /// </summary>
        public static string TrustedInvestors {
            get {
                return ResourceManager.GetString("TrustedInvestors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL_ {
            get {
                return ResourceManager.GetString("URL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dialog.
        /// </summary>
        public static string UserDialog {
            get {
                return ResourceManager.GetString("UserDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERNAME.
        /// </summary>
        public static string USERNAME_ {
            get {
                return ResourceManager.GetString("USERNAME_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        public static string UsersManagement {
            get {
                return ResourceManager.GetString("UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans and investments between people at fair rates.
        /// </summary>
        public static string UsersText {
            get {
                return ResourceManager.GetString("UsersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are Here to Help You.
        /// </summary>
        public static string WeareHeretoHelpYou {
            get {
                return ResourceManager.GetString("WeareHeretoHelpYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WE REACHED 1 BILLION IN LOANS GIVEN OUT!.
        /// </summary>
        public static string welcome_top_banner {
            get {
                return ResourceManager.GetString("welcome_top_banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why People Choose Us.
        /// </summary>
        public static string WhyPeopleChooseUs {
            get {
                return ResourceManager.GetString("WhyPeopleChooseUs", resourceCulture);
            }
        }
    }
}
