//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDroidApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoanDroidApp.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Reserved.
        /// </summary>
        public static string AllReserved {
            get {
                return ResourceManager.GetString("AllReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contactus {
            get {
                return ResourceManager.GetString("Contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast &amp; Easy Application Process.
        /// </summary>
        public static string FastEasyApplicationProcess {
            get {
                return ResourceManager.GetString("FastEasyApplicationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Loan Services We Offers.
        /// </summary>
        public static string FindLoanServicesWeOffers {
            get {
                return ResourceManager.GetString("FindLoanServicesWeOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work?.
        /// </summary>
        public static string howitworks {
            get {
                return ResourceManager.GetString("howitworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal users.
        /// </summary>
        public static string InternalUsers {
            get {
                return ResourceManager.GetString("InternalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want a loan.
        /// </summary>
        public static string Iwantloan {
            get {
                return ResourceManager.GetString("Iwantloan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to lend.
        /// </summary>
        public static string Iwanttolend {
            get {
                return ResourceManager.GetString("Iwanttolend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News from Loan Company.
        /// </summary>
        public static string LatestNewsfromLoanCompany {
            get {
                return ResourceManager.GetString("LatestNewsfromLoanCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Calculator.
        /// </summary>
        public static string LoanCalculator {
            get {
                return ResourceManager.GetString("LoanCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans and &lt;strong class=&quot;text-highlight&quot;&gt;investments&lt;/strong&gt;.
        /// </summary>
        public static string slider01_title {
            get {
                return ResourceManager.GetString("slider01_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of our Awesome Testimonials.
        /// </summary>
        public static string SomeofourAwesomeTestimonials {
            get {
                return ResourceManager.GetString("SomeofourAwesomeTestimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are Here to Help You.
        /// </summary>
        public static string WeareHeretoHelpYou {
            get {
                return ResourceManager.GetString("WeareHeretoHelpYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WE REACHED 1 BILLION IN LOANS GIVEN OUT!.
        /// </summary>
        public static string welcome_top_banner {
            get {
                return ResourceManager.GetString("welcome_top_banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why People Choose Us.
        /// </summary>
        public static string WhyPeopleChooseUs {
            get {
                return ResourceManager.GetString("WhyPeopleChooseUs", resourceCulture);
            }
        }
    }
}
